### ISSUE TITLE
Device class None, state class and unit None 

### ISSUE THREAD

**Issue by jlatvala** [Racailloux/home-assistant-pijuice#16]
This is logged on every reboot:

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:597
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:45:59 (2 occurrences)
Last logged: 12:45:59

Sensor sensor.pijuice_battery_status has device class None, state class and unit None thus indicating it has a numeric value; however, it has the non-numeric value: normal (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.pijuice_power_input_io_status has device class None, state class and unit None thus indicating it has a numeric value; however, it has the non-numeric value: present (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by Racailloux** [comment]
This is actually surprising. I tested again on a fresh setup and it doesn't complains about the type of the "status".
The texted (with translation) sensors should still be setup as 'None' device & state class.

Can you confirm me the sensors' setup in your configuration.yaml?

**Comment by jlatvala** [comment]
HA: Home Assistant 2023.3.6

configuration.yaml:

```
# Sensors...
sensor:

# PiJuice HAT
  - platform: pijuice
    monitored_conditions:
      - battery_status
      - power_input_io_status
      - charge
# See https://github.com/Racailloux/home-assistant-pijuice
```
